name: URBANDENIZENS
favicon: null
layout_spectrum: 0.83321
typography_spectrum: 0.60365
title: 'Design & Research Collective Studio'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c1c1c1'
    - '#fbf336'
    - '#747474'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
