name: URBANDENIZENS
favicon: null
layout_spectrum: 0.9922
typography_spectrum: 0.60365
title: 'Design & Research Collective Studio'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c2e3c4'
    - '#5c5c5c'
    - '#000000'
    - '#adadad'
  brandStrength: 0.6338583086617291
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
