name: URBANDENIZENS
favicon: null
layout_spectrum: 0.29663479304872453
typography_spectrum: 0.35975165851414204
title: 'Design & Research Collective Studio'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6338583086617291
  lightness: 0.4431306985206902
  saturation: 0.5002417247742414
  rhythmicContrast: 0.8059216833207756
purpose: []
